### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by cosmos1978** [Whilser/GyverLamp#10]
I did a full translation to English.
Are you interested in the code ?

**Comment by cosmos1978** [comment]
The webserver part is also translated. 

ust let me know and I will email the code

**Comment by Stokstaart** [comment]
> I did a full translation to English.
> Are you interested in the code ?

I am! Having some issues doing the translationsby myself!

**Comment by cosmos1978** [comment]
I prefer to give it to whilser so he can continue with the english version which would target a much larger  group of electronics enthousiasts.

**Comment by Stokstaart** [comment]
I totale onderstand. I have no intentions of publishing it, it would be just for personal use!

**Comment by cosmos1978** [comment]
I forked the code with translation here

[https://github.com/cosmos1978/GyverLamp/tree/Translation]

**Comment by vortigont** [comment]
@cosmos1978 I'm interested in publicly available english version, might involve more people in there. Now I'm working on code refactoring, how about try to merge in your translation?

**Comment by cosmos1978** [comment]
Sure, I will give it a go this evening.
is it this repo ? https://github.com/vortigont/GyverLamp/tree/featured

I will fork it and add the translation. But perhaps it is better to wait until your work is done and Whilser includes it in his master branch ?

**Comment by Whilser** [comment]
Ok, thanks for the work. I'll consider best way to integrate localization.

**Comment by Whilser** [comment]
I added English localization to the firmware. To switch to English localization, just uncomment the ENG directive.

**Comment by vortigont** [comment]
@cosmos1978 it is, testers/bug reports are welcome :)
it's gonna take a while to clean up all messy places, lot's of ideas to implement.
