### ISSUE TITLE
New effect pendulul

### ISSUE THREAD

**Issue by cosmos1978** [Whilser/GyverLamp#16]
really nice effect. I also added the possibility to change the colorpalette with the scale control.

You have 2 open pull requests :-)

**Comment by Whilser** [comment]
ok, I will see as soon as I have free time. Pull requests are best done not by completely replacing files, but by making changes to sections of code. It’s easier to edit and make changes.

**Comment by cosmos1978** [comment]
shouldn't a merge be automatically ?
But I will remember the next time I add some code :-)

**Comment by cosmos1978** [comment]
I added a new effect ( patternwave ) that I made myself using 2 sine functions. fully transformable using scale.
I also used git to update the changes :-) so no more full files being updated.

**Comment by Whilser** [comment]
Finally, I added  warm light and a pendulum effects. I added manually because Initially pull request was made without using git. The wave effect seemed incomplete to me, so I did not add it for a now.
