### ISSUE TITLE
HomeKit integration without bridge?

### ISSUE THREAD

**Issue by alekseyp** [Whilser/GyverLamp#17]
Привет! Спасибо всем за работу и отличный форк!

Заказал платы и пока жду:

Реально ли, и есть ли смысл вообще, сделать минимальную интеграцию с HomeKit, чтобы не запускать Home Bridge, а сделать как можно более native?

Что-то типа https://github.com/RavenSystem/esp-homekit-devices ?

**Comment by Whilser** [comment]
Смысла особого нет т.к. ресурсы ESP и так практически под завязку забиты, плюс HAA - это вообще отдельный проект. Поэтому если нужен HomeKit, то лучше использовать HomeBridge.

**Comment by alekseyp** [comment]
Ok, я так и подозревал. Спасибо!
