### ISSUE TITLE
webserver alert page

### ISSUE THREAD

**Issue by cosmos1978** [Whilser/GyverLamp#22]
I noticed that the alert page does not load anymore.

Can you have a look at that ?

Thanks.

**Comment by Whilser** [comment]
What do you mean? Explain

**Comment by cosmos1978** [comment]
It seemed I had 1 wrong setting in arduino when flashing my nodemcu. Fixed that just now and all is working now.

**Comment by cosmos1978** [comment]
PS the weather stuff is ready. Very happy with the result
