### ISSUE TITLE
Ota 

### ISSUE THREAD

**Issue by halk415** [Whilser/GyverLamp#26]
Подскажите как шить через сетевой порт. В ардуино IDE он просто не появляется в в выборе порта...

**Comment by Whilser** [comment]
В Arduino IDE он должен появляться. Важно чтобы компьютер и лампа была подключена к одной точки доступа WiFi, при этом на роутере должен быть разрешён мультикаст и mDNS. Обычно все это включено уже по-умолчанию. Как вариант, перезагрузить лампу, потом через пару минут запустить Arduino IDE, сетевой порт может не сразу появиться в некоторых случаях, надо подождать немного и попробовать снова его выбрать. А далее как обычно - нажать загрузить.

**Comment by halk415** [comment]
Спасибо получилось
