### ISSUE TITLE
Проблема с эффектом «Огонь»

### ISSUE THREAD

**Issue by sergeich5** [Whilser/GyverLamp#27]
Прошивка: GyverLamp_v1.5_MQTT

При включении данного режима, диоды начинают загораться, но менее чем через секунду вырубаются (словно перезагружается там что-то) на секунды 3-4, затем пытаются вновь включиться на секунду и снова выключаются и так вечно

**Comment by Whilser** [comment]
Это только на эффекте огонь? Пробовал ESP заменить?

**Comment by balbulator** [comment]
Это может быть питание

**Comment by sergeich5** [comment]
> Это только на эффекте огонь? Пробовал ESP заменить?

> Это может быть питание

только на эффекте огонь, питание вроде хватает (яркость ставлю на 20). Попробую протестировать на другой ESP

@Whilser @balbulator
