### ISSUE TITLE
Интеграция с датчиком со2 и температуры

### ISSUE THREAD

**Issue by lexxnsk** [Whilser/GyverLamp#32]
Есть ли возможность добавить работу с датчиками mh-z19b и bme280?

**Comment by lexxnsk** [comment]
Могу попробовать сделать сам - подскажите куда копать.

**Comment by Whilser** [comment]
Теоретически это возможно, но на практике это может привести к дополнительной нестабильности. Пример скетча подключения датчика углекислого газа можно найти в сети, например, здесь - https://arduino-technology.ru/coding/hardware/mhz19b-sensor/ Все что останется, это добавить запрос статуса с датчика в таймер (существующий либо создать свой). 

Наиболее оптимальным вариантом будет подключить эти датчики на отдельную ESP и залить туда прошивку ESPHome, Tasmota и т.п.

**Comment by lexxnsk** [comment]
Спасибо за ответ.
