### ISSUE TITLE
Добавить поддержку Google Home / Alexa

### ISSUE THREAD

**Issue by bvitaliyg** [Whilser/GyverLamp#6]
Было бы круто иметь нативную интеграцию с этими системами умного дома, либо же, если такое можно проксировать через Home Assistant/MQTT, инструкцию по интеграции этого добра с Google Home/Alexa.

**Comment by Whilser** [comment]
Есть варианты сделать это через плагин HomeBridge. 

https://sprut.ai/client/article/1699
https://github.com/oznu/homebridge-gsh

Решение не тестировалось, но судя по описанию должно работать.
