### ISSUE TITLE
extra effect

### ISSUE THREAD

**Issue by cosmos1978** [Whilser/GyverLamp#8]
This seems like an effect that can easily be integrated.

https://gist.github.com/kriegsman/5adca44e14ad025e6d3b

**Comment by Whilser** [comment]
Hi! The main problem with this sketch is that it uses the SmartMatrix library for Teensy USB Development Board, but we usually use NodeMCU board, based on ESP8266 Chip on board.

**Comment by cosmos1978** [comment]
Ok I see now.

But I did find this one

https://gist.github.com/anonymous/68298debac462330719b

uses only fastled library and looks realy nice.
http://www.youtube.com/watch?v=EC1MuRhXd1U

http://www.youtube.com/watch?v=0Ehj7sEwOy4

**Comment by cosmos1978** [comment]
This guy has a huge collection

https://www.youtube.com/channel/UCkOEj4gOrUq1rbKElkmdo9g

**Comment by cosmos1978** [comment]
https://github.com/StefanPetrick/FunkyClouds

**Comment by Whilser** [comment]
Ok, thank you. I'll see later which of these effects will look good on the lamp. Some of them  I will add maybe when I have time for this.
