### ISSUE TITLE
Эффект мигалки

### ISSUE THREAD

**Issue by iswitch** [Whilser/GyverLamp#9]
Добавьте пожалуйста эффект мигалки (проблесковый маячок). Чтоб полоска выбранного цвета бегала по кругу с заданной скоростью, ну и можно по краям полоски сделать рассеивание. Спасибо)

**Comment by Whilser** [comment]
Добавил эффект "полицейская сирена" в последнем обновлении. Удобно для использовании в сценариях с предупреждениями. Масштабирование меняет стиль эффекта, скорость - скорость мерцания.

**Comment by iswitch** [comment]
Спасибо)

**Comment by sashayohan** [comment]
Добавьте, эффект, что бы она крутилась по кругу. Как на старых машинах.
По типу такой https://youtu.be/NYUObVYJtGA
Лампа больше такую форму мигалки напоминает

**Comment by sashayohan** [comment]
Ну уже почти получилось) Только почему то скорость рывками при 0, а при 255 совсем медленно.
И два отдельных цвета реально сделать? (только красный или только синий, и оранжевый до кучи, чтобы не вместе)

**Comment by Whilser** [comment]
Чтобы убрать один из огоньков нужно закомментировать строчку drawPixelXY(ppp5, y, CRGB::Blue); Здесь вместо CRGB::Blue можно поставить свой цвет какой хочешь из палитры. При скорости 0 возможно не успевает отрабатывать. Бегунок скорости здесь по сути задает интервал времени между каждой прорисовкой фрейма. По сути когда ноль - получается цикл перерисовки выполняется каждый раз при входе в цикл эффекта.
